FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
#COPY --chown=node:node package.json .
RUN npm config set strict-ssl false --global
RUN npm install npm -g --ca=""

COPY . .
#COPY --chown=node:node . .
USER node

CMD ["npm", "run", "start"]