FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

#working local
#RUN npm config set strict-ssl false --location=global
#RUN npm install npm -g --ca=""

RUN npm install

COPY . .

#working local
#USER node

CMD ["npm", "run", "start"]